- hosts: all
  gather_facts: True
  become: yes
  become_method: sudo

  tasks:

  - name: Upgrade to python 2.7.10 ( necessary to install nodejs)
    apt_repository:
      repo: 'ppa:fkrull/deadsnakes-python2.7'

  - name: Upgrade python
    apt:
      name: python2.7
      state: present
      update_cache: yes

  - name: Import the NodeSource GPG key into apt
    apt_key:
      id: 68576280
      url: "https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280"
    tags:
      - node
      - download_node

  - name: Download node setup program
    get_url: url=https://deb.nodesource.com/setup_6.x dest=/tmp/nodeinstall mode=0700
    tags:
      - node
      - download_node

  - name: Run node setup
    shell: "/tmp/nodeinstall"
    tags:
      - node
      - install_node

  - name: Install node
    apt:
      name: nodejs
      state: present
      update_cache: yes
    tags:
      - install_node

  - name: install pm2 process manager for node
    npm: name=pm2 global=yes
    tags:
      - pm2_install

  - name: make /srv/opt/ folder with permissions for www-data
    file: path="/srv/opt/" state=directory recurse=true owner='www-data' group='www-data' mode=775
    tags:
      - install_hello_world_application

  - name: check engine status
    shell: pm2 info hello-world
    register: pm2_hello_world_status
    ignore_errors: True
    tags:
      - pm2_run

  - name: install hello world application
    copy: src=files/srv/opt/hello-world.js dest=/srv/opt/hello-world.js mode=0600
    tags:
      - install_hello_world_application

  - name: start hello world application running
    shell: pm2 start /srv/opt/hello-world.js -x --name hello-world
    when: pm2_hello_world_status.stderr == "[PM2][WARN] hello-world doesn't exist"
    tags:
      - pm2_run

  - name: create start up script for pm2
    command: pm2 save
    tags:
      pm2_run



  - name: install nginx
    apt:
      name: nginx
      state: present
      update_cache: yes
    tags:
       - install_nginx

  - name: install proxy to nodejs
    template:
      src: 'templates/etc/nginx/sites-available/default'
      dest: '/etc/nginx/sites-available/default'
      owner: 'root'
      group: 'root'
      mode: '0644'
    tags:
      - install_proxy


# vim:ft=ansible:
