- hosts: all
  gather_facts: True
  become: yes
  become_method: sudo

  tasks:

  - name: install nginx
    apt:
      name: nginx
      state: present
      update_cache: yes
     tags:
       - install_nginx
